[Rule]
DOMAIN-SUFFIX,supercell.com

[URL Rewrite]
^https:\/\/store\.supercell\.com\/zh-cn\/([^?]+)(\?.*)?$ https://store.supercell.com/en/$1$2 302

[MITM]
hostname = store.supercell.com,*.supercell.com