[Rule]
DOMAIN-SUFFIX,supercell.com

[URL Rewrite]
# 中文页面改英文（匹配 /zh-cn/）
^https:\/\/store\.supercell\.com\/zh-cn\/ https://store.supercell.com/en/ 302

# free-gift活动保留
^https:\/\/store\.supercell\.com\/zh-cn\/clashroyale\?campaign=free-gift https://store.supercell.com/en/clashroyale?campaign=free-gift 302

[MITM]
hostname = store.supercell.com, *.supercell.com